In [1]:
import numpy as np

##### Creating an array

In [12]:
arr=np.array([1,2,3])
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
print('dimensions',arr.ndim)
print('shape',arr.shape)

dimensions 1
shape (3,)


In [14]:
#creating a two dimensions array
arr2=np.array([[1,2],[3,4]])
print(arr2)
print(arr2.ndim)

[[1 2]
 [3 4]]
2


In [15]:
#creating a 3D array
threeD=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
threeD.ndim

3

In [81]:
print(threeD.shape)
print(threeD)

(1, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [78]:
arr3=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
            [[13,14,15],[16,17,18]]
              ])

In [82]:
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3
(3, 2, 3)


In [19]:
print(arr3.shape)

(3, 2, 3)


In [24]:
#we can also take list of elements and convert it into array
L=[[[1,2,3],[4,5,6],[7,8,9]]]
L=np.array(L)
print(L)
print(type(L))
print(L.ndim,L.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3 (1, 3, 3)


## INDEXING AND SLICING: 

In [25]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [26]:
arr3[0,0,0]

1

In [27]:
arr3[0,0,1]

2

In [28]:
arr3[0,0,2]

3

In [29]:
arr3[0,1,0]

4

In [ ]:
arr3[2,1,2]

In [4]:
matrix=np.arange(-18,0,1).reshape(3,2,3)
matrix

array([[[-18, -17, -16],
        [-15, -14, -13]],

       [[-12, -11, -10],
        [ -9,  -8,  -7]],

       [[ -6,  -5,  -4],
        [ -3,  -2,  -1]]])

In [12]:
matrix[0:,0:1,2:]
matrix[0]

array([[-18, -17, -16],
       [-15, -14, -13]])

In [32]:
matrix[0:,1:,:]

array([[[-15, -14, -13]],

       [[ -9,  -8,  -7]],

       [[ -3,  -2,  -1]]])

In [33]:
matrix

array([[[-18, -17, -16],
        [-15, -14, -13]],

       [[-12, -11, -10],
        [ -9,  -8,  -7]],

       [[ -6,  -5,  -4],
        [ -3,  -2,  -1]]])

In [34]:
matrix[2,1,2]=100
matrix

array([[[-18, -17, -16],
        [-15, -14, -13]],

       [[-12, -11, -10],
        [ -9,  -8,  -7]],

       [[ -6,  -5,  -4],
        [ -3,  -2, 100]]])

In [35]:
#retrieving using indexing
  # creating a 3x4 matrix
I=np.arange(0,12).reshape(3,4)
I

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
print(I.ndim)

2


In [37]:
I[2,3]  # for 2D

11

In [38]:
I[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [39]:
#indexing on 3D
D=np.arange(0,27).reshape(3,3,3)

In [40]:
D

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
D[0]
#D[1]
#D[2]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
D[0,2]

array([6, 7, 8])

## creating matrix:

In [48]:
import numpy as np

In [49]:
Z=np.arange(0,10)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
Y=np.zeros(10)
Y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
X=np.ones(10,dtype='int')
X

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [52]:
V=np.full((2,2),7)
V

array([[7, 7],
       [7, 7]])

In [53]:
v=np.full((3,4),10)
v

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [88]:
U=np.eye(3,3)
U

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
u=np.eye(4,4,dtype=int)
u

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [56]:
r=np.random.random((2,2))
r

array([[0.37532302, 0.34606125],
       [0.50187751, 0.68204816]])

In [15]:
R=np.linspace(0,10,10)
R

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [16]:
K=np.empty((3,2))
K

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# COPIES AND VIEWS:

In [59]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
K=array
K

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
print(id(K))
print(id(array))

2189582584048
2189582584048


In [ ]:
#this is shallow copy
#if we change values in K it also changes the value in original array

In [62]:
K[0,0]=10
K

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [63]:
array

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [89]:
#new matrix
A=np.arange(11,20).reshape(3,3)
A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [65]:
B=A.copy() #this is deep copy 
B          # though we are tryng to change the value in B it doesnt effect the values in A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [66]:
B[2,2]=10
B


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 10]])

In [90]:
A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [68]:
G=np.arange(0,9).reshape(3,3)
G

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
F=G.view()
F

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
G[0,0]=99
G

array([[99,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [71]:
F

array([[99,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [76]:
id(F)

2189582606464

In [75]:
id(G)

2189582529360

### Operations in numpy arrays 
##### Add,Sub,Mul,Div

In [ ]:
  # creating a matrix
matrix_A=np.array([[1,2],[3,4]])
matrix_B=np.array([[7,8],[5,6]])
print('A',matrix_A)
print()
print('B',matrix_B)


In [ ]:
# adding matrix_A and matrix_B
print(matrix_A+matrix_B)

In [ ]:
print(np.add(matrix_A,matrix_B))

In [ ]:
 #subract
print(np.subtract(matrix_A,matrix_B))

In [ ]:
print(matrix_A-matrix_B)

In [ ]:
print(matrix_A)
print()
print(matrix_B)

In [ ]:
  #matrix multiply
print(matrix_A*matrix_B)

In [ ]:
print(np.multiply(matrix_A,matrix_B))

In [ ]:
print(matrix_A.dot(matrix_B))

In [ ]:
  #matric divide
print(np.divide(matrix_A,matrix_B))

In [ ]:
print(matrix_A/matrix_B)

In [ ]:
print(np.sin(matrix_A))

In [ ]:
print(np.cos(matrix_B))

## BROADCASTING :

In [7]:
B=np.arange(9).reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
A=np.array([1])

In [21]:
B+A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
C=np.array([1,10,20])
B+C

array([[ 1, 11, 22],
       [ 4, 14, 25],
       [ 7, 17, 28]])

In [11]:
D=np.array([2,3,4])
B+D

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

### STATISTICS RELATED OPERATIONS:-

In [26]:
M=np.array([2,4,6])
M.mean()

4.0

In [13]:
N=np.array([[1,2],[2,4]])
N.mean()

2.25

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [29]:
O=np.arange(1,10).reshape(3,3)
print(O)
O.mean(axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [30]:
O.mean(axis=1)

array([2., 5., 8.])

In [31]:
M.std()

1.632993161855452

In [32]:
M.min()

2

In [33]:
O.max()

9

# ARRAY SHAPE MANIPULATION:-

In [16]:
Q=np.arange(0,15).reshape(3,5)
Q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
q=Q.ravel()
q[0]=-1
q

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
Q

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
#flatten
P=np.arange(0,9)
P

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
Z=P.flatten()
Z[-1]=100
Z

array([  0,   1,   2,   3,   4,   5,   6,   7, 100])

In [22]:
P

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
#resize
new=np.arange(4)
new.resize((8,))
new

array([0, 1, 2, 3, 0, 0, 0, 0])

In [24]:
new1=new
new1.resize((12,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [74]:
#sort
matrixx=np.arange(25,0,-1).reshape(5,5)
matrixx

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [75]:
matrixx.sort(axis=1)
matrixx

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [25]:
#adding a new dimension
Aa=np.array([1,2,3])
Aa.shape

(3,)

In [26]:
b=Aa[:,np.newaxis]
b.shape
b.ndim

2

In [ ]:
#some more methods frequently used in numpy

In [28]:
S=np.arange(1,4)
np.all(S)

True

In [111]:
s=np.arange(0,2)
np.all(s)

False

In [3]:
ar=np.array([2,2,2,0])
np.any(ar)

True

In [6]:
X=np.array([[1,2,3],[4,5,6]])
print(X)
X.T

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])