In [44]:
import numpy as np

# COPIES AND VIEWS:

In [45]:
array=np.arange(1,10).reshape(3,3)

In [46]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
K=array

In [48]:
K

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
print(id(K))
print(id(array))

2273813818544
2273813818544


In [50]:
#this is shallow copy
#if we change values in K it also changes the value in original array

In [51]:
K[0,0]=10
K

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [52]:
array

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [53]:
A=np.arange(11,20).reshape(3,3)
A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [54]:
B=A.copy() #this is deep copy 
B          # though we are tryng to change the value in B it doesnt effect the values in A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [55]:
B[2,2]=10
B

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 10]])

In [56]:
A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [57]:
G=np.arange(0,9).reshape(3,3)
G

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
F=G.view()
F

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
G[0,0]=99
G

array([[99,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [60]:
F

array([[99,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

# LOGICAL OPERATIONS

In [61]:
a=np.array([2,3,4,1,0]) 
b=np.array([2,3,4,0,0])
np.logical_or(a, b)

array([ True,  True,  True,  True, False])

In [62]:
np.logical_and(a, b)

array([ True,  True,  True, False, False])

In [63]:
np.logical_xor(a, b)

array([False, False, False,  True, False])

In [64]:
np.logical_not(a)

array([False, False, False, False,  True])

# Transcendental Operations:

In [65]:
N=np.array([0,45,90,180,360])
np.sin(N)

array([ 0.        ,  0.85090352,  0.89399666, -0.80115264,  0.95891572])

In [66]:
np.cos(N)

array([ 1.        ,  0.52532199, -0.44807362, -0.59846007, -0.28369109])

In [67]:
np.log(N)

<ipython-input-67-aabe0ddd27b9>:1: RuntimeWarning: divide by zero encountered in log
  np.log(N)


array([      -inf, 3.80666249, 4.49980967, 5.19295685, 5.88610403])

In [68]:
np.exp(N)

array([1.00000000e+000, 3.49342711e+019, 1.22040329e+039, 1.48938420e+078,
       2.21826530e+156])

# Basics mathematical operations

In [69]:
matrix_A=np.array([[1,2],[3,4]])
matrix_B=np.array([[7,8],[5,6]])
print('A',matrix_A)
print()
print('B',matrix_B)


A [[1 2]
 [3 4]]

B [[7 8]
 [5 6]]


In [70]:
# adding matrix_A and matrix_B
print(matrix_A+matrix_B)

[[ 8 10]
 [ 8 10]]


In [71]:
print(np.add(matrix_A,matrix_B))

[[ 8 10]
 [ 8 10]]


In [72]:
 #subract
print(np.subtract(matrix_A,matrix_B))

[[-6 -6]
 [-2 -2]]


In [73]:
print(matrix_A-matrix_B)

[[-6 -6]
 [-2 -2]]


In [74]:
print(matrix_A*matrix_B)

[[ 7 16]
 [15 24]]


In [75]:
print(np.multiply(matrix_A,matrix_B))

[[ 7 16]
 [15 24]]


In [76]:
print(matrix_A.dot(matrix_B))

[[17 20]
 [41 48]]


In [77]:
#matrix divide
print(np.divide(matrix_A,matrix_B))

[[0.14285714 0.25      ]
 [0.6        0.66666667]]


In [78]:
print(matrix_A/matrix_B)

[[0.14285714 0.25      ]
 [0.6        0.66666667]]


# Fancy Indexing

In [79]:
new=np.arange(0,10)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
new[2:6]

array([2, 3, 4, 5])

In [81]:
new[2:6]=0
new

array([0, 1, 0, 0, 0, 0, 6, 7, 8, 9])

In [82]:
S=np.arange(11,20).reshape(3,3)
S

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [83]:
R=(S%2==0)
R

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [84]:
s=S[R]
s

array([12, 14, 16, 18])

In [86]:
S[R]=90
print(S)

[[11 90 13]
 [90 15 90]
 [17 90 19]]
